### ISSUE TITLE
Missing picture in login

### ISSUE THREAD

**Issue by Alan01** [linuxmint/mdm#102]
LM 17 Cinnamon
When using an HTML theme in MDM, the picture of the user (administrator) is not shown in the login screen. The picture of other users are shown. Switch to a GDM theme and the picture is shown.

**Comment by stevejarvis** [comment]
Hey, I'm seeing the same issue. On a machine with two users one pic shows up at the login screen, the other does not (and it's the user in the sudoers that does not). The pic was set via the Users and Groups settings page. Here's some of the other debug info requested:

    % ls -al .face                                      
    -rw-r--r-- 1 sjarvis sjarvis 19147 Jan 30 19:32 .face
    % file .face                                           
    .face: PNG image data, 96 x 96, 8-bit/color RGB, non-interlaced
    % whoami                                                 
    sjarvis

**Comment by xrazvan** [comment]
Hi, same issue here. Using Mint-X theme with 2 users. Apparently this doesn't work for neither of the users because the home dir is encrypted. Is there any workaround to show the picture even if the home dir is encrypted?

**Comment by cnlohr** [comment]
I think I found a solution.  Not only do you need to make sure you have your pictures in a folder that's unencrypted, you also need to make sure you have r and x rights over all paths to that folder.  I have no idea why it wants execute privlieges but it does.

Be sure to:

   chmod o+x g+x o+r g+r * -R 

To the folder.
