### ISSUE TITLE
Webkit greeter: Include user's home directory in user data

### ISSUE THREAD

**Issue by gandalfx** [linuxmint/mdm#109]
The `mdm_add_user` function call currently passes a username, gecos data and a login status for each user.
Most themes rely on the user's home directory being `/home/<username>`, where they will find the .face file, among other things. However a user's home directory can be somewhere else, in which case using that hardcoded location will fail.
It should be easy enough to pass the home directory location as well.

In fact it is possible to retrieve it via ajax (jQuery or pure XMLHttpRequest) from /etc/passwd:
```JS
$.get("file:///etc/passwd", parserCallback);
```
While that is actually quite useful it is also worrying considering how easy it may be to inject malicious js code that will unveil sensitive information. That is why web browsers are usually a lot more restrictive about what resources may be accessed (In Firefox you can only ajax-GET resources from the same directory as the current HTML file).

**Comment by clefebvre** [comment]
We're passing the avatar URL now (which isn't always in the home directory).
