### ISSUE TITLE
Webkit greeter: More API options (login, session selection)

### ISSUE THREAD

**Issue by gandalfx** [linuxmint/mdm#110]
Currently the way to communicate information from within JavaScript to MDM is to call the `alert` builtin function with special strings, like `SHUTDOWN###`. MDM will then react in some more or less predictable way. I have found the following problems:
- When alerting `USER###<username>` and `LOGIN###<password>` sequentially without waiting for `mdm_noecho` to be called, MDM will react by calling `mdm_set_current_user(<password>)`. In most cases this will result in the password being displayed in clear text.
  The reason for this is, that MDM expects the authentication to be a two step process (send username, wait, send password).
  When I stumbled upon this issue I was trying to create a theme that would have two input fields (username and password) that would get evaluated together. Most online login forms work like that.
  Ideally it should be possible to alert `LOGIN###<password>` at any time without getting any clear text back. An alternative might be to extend the syntax to `LOGIN###<username>###<password>`.
  I was able to circumvent the problem by creating an eventlistener that will wait for `mdm_noecho` to be called, before sending the password, but that is hardly optimal.
- While shutdown, restart etc. have their own `FORCE-*###` alerts, selecting a different session will always result in a (non-HTML) popup, asking if the selection should be made permanent. That is very ugly and could be easily done by JavaScript. I suggest adding something like a `MAKE-SESSION-PERMANENT###` alert option.

**Comment by callagg2** [comment]
Vaguely related to the above issue
Login screen, it still is confusing.
 Could we
-> move the image square over to the right above the "ok" button. 
-> on the left , start with computer name at top, under that, show username input box, and under that, show the password input box. 

At bootup, 
Grey/fade out your username box (with a downward arrow on the right should you want to change user) 
This way you will always know its your password being asked for.

(here is a really really rough version)
![login_screen](https://cloud.githubusercontent.com/assets/15323690/10728962/0754ef00-7bde-11e5-8c27-699a7c5c9c39.png)

**Comment by gandalfx** [comment]
@callagg2 That really has nothing to do with this issue at all. You're talking about a specific theme, so you might want to head over to the repo where the themes are stored: https://github.com/linuxmint/mint-mdm-themes/issues
