### ISSUE TITLE
MDM does not respect nvidia overscan / metamode / panning settings

### ISSUE THREAD

**Issue by DanielHeath** [linuxmint/mdm#121]
I'm using an nvidia card to drive my TV via HDMI.
My `xorg.conf` has the following:
`"metamodes" "DFP-1: 1920x1080 @1808x1017 {ViewPortOut=1808x1017+56+31, ViewPortIn=1920x1080}"`

MDM is trying to draw everything at 1920x1080 instead of 1808x1017 (so e.g. the bar across the bottom is invisible).

I can access this stuff by turning on panning, but I'd prefer to have the screen render the correct size.

**Comment by clefebvre** [comment]
Hi,

Please have a look at http://segfault.linuxmint.com/2015/08/configuring-the-mdm-login-screen-for-multiple-monitors/ for the resolution.

If it's to do with hidpi, also check the output of /usr/bin/mdm-get-monitor-scale.

Last but not least, check the output of https://raw.githubusercontent.com/linuxmint/mdm/master/files/usr/bin/mdm-get-monitor-scale as it was recently improved. (don't overwite your own /usr/bin/mdm-get-monitor-scale... as that wouldn't be compatible with your version of MDM.. if you want to do that, please make sure to recompile mdm using the git master version).

**Comment by DanielHeath** [comment]
After fiddling with it for a week or two I went back to Ubuntu and now everything works out of the box.
