### ISSUE TITLE
MDM Keyboard-Layout stay in english when installing with external Keyboard

### ISSUE THREAD

**Issue by Daniel12344** [linuxmint/mdm#128]
I installed Mint 17.1 RC Cinnamon in german language and also select german keyboard. During the installation I used a wireless keyboard (Logitech K400r). After the reboot the systemlanguage and keyboard setting is german, but in the login-screen the keyboard layout is still in english. This also happend with Mint 17 (and i think also 16) so it’s not a new bug, but it’s still there.
This only happens when I use the external keyboard during the installation, no problems when i use only the internal keyboard.

On Mint 17 xfce i found a workaround somwhere in the net, but I don't think that that's a propper solution. After i add
"/usr/bin/setxkbmap de"
bevor the "exit 0" in "/etc/mdm/Init/Default" MDM use the german layout.

Please tell me if you need more information.

**Comment by gregeva** [comment]
I too have experienced this issue for quite some time now.  In my case, the specifics are different however:
* installation on a laptop using only built-in FR-FR keyboard
* installation keyboard layout was FR-FR
* added EN-US keyboard layout after installation and set to user and system default
* the language/layout flag next to the user in the MDM login screen now changes to EN-US, however keymap remains FR-FR
This last point was somewhat addressed in the 17.1 Rebecca (Cinnamon) release I believe, as previously the flag did not change to reference the users keymap settings.
I have experienced this in both Cinnamon and MATE desktop environments.

**Comment by clefebvre** [comment]
The greeter should use the layout defined in /etc/default/keyboard.

This file supports multiple layouts and even key switches if you want.

**Comment by clefebvre** [comment]
The issue posted by @Daniel12344 should be fixed in MDM 2.0.15, thanks to this commit: 

https://github.com/linuxmint/mdm/commit/a293167340624021e1b379118a647a97da9dd550
