### ISSUE TITLE
MDM is replacing another package with the same name

### ISSUE THREAD

**Issue by darealshinji** [linuxmint/mdm#133]
There is another package with the same name:
http://packages.ubuntu.com/mdm
https://packages.debian.org/mdm

**Comment by jristz** [comment]
so this raise the isue if mdm here stand for an achronym or not because if stand for one maybe using the full name could help.

**Comment by darealshinji** [comment]
I think Mint's MDM stands for "MDM Display Manager".
So `mdm-display-manager` maybe?

**Comment by jristz** [comment]
That solution could apply to the other mdm with the conflict.
As a note in arch (in they AUR) they resolve the problem renaming this to mdm-display-manager (package name).
als I want think that mdm-display-manager is a recursive achronym where the mdm in the name (mdm-display-manager) stand for mint-display-manager.

**Comment by darealshinji** [comment]
Why was this closed? This issue is still present!

**Comment by xenopeek** [comment]
As you may have read on the latest Monthly News on the blog, we're bug squashing and changing the way requests are handled. For requests like these the issue doesn't need to remain open once the request is clear and understood, and doesn't require further information gathering,
