### ISSUE TITLE
MDM 1.8.3 Memory Leak  (Cinammon 2.4.6)

### ISSUE THREAD

**Issue by valsodarg** [linuxmint/mdm#135]
I seem to have encountered a memory leak in MDM after running for several days (4 days) with multiple suspend/sleeps. Currently the mdm process is consuming 3.0 GB of memory. I do not know how to conduct memory leak analysis of a running system process but am willing to do so.

Here is the pmap of the process:
 pmap -XX 1586
1586:   mdm
         Address Perm   Offset Device   Inode    Size     Rss     Pss Shared_Clean Shared_Dirty Private_Clean Private_Dirty Referenced Anonymous AnonHugePages Swap KernelPageSize MMUPageSize Locked                   VmFlagsMapping
        006a8000 rw-p 00000000  00:00       0     264     264     198            0          132             0           132        160       264             0    0              4           4      0    rd wr mr mw me ac sd  [heap]
        006ea000 rw-p 00000000  00:00       0 3111692 3111600 3111600            0            0             0       3111600    3102508   3111600       2875392    0              4           4      0    rd wr mr mw me ac sd  [heap]

**Comment by fomich-artem** [comment]
Hello! Same trouble... It is fixed now (in latest mint release)?

**Comment by anibyl** [comment]
mdm: 8.5 GB after 2 days of uptime. It is crazy! MDM 2.0.7, Mint 17.3, Cinnamon 2.8.6.

**Comment by siskulous** [comment]
Confirming, same issue. It just started this week, but htop shows mdm using 3gb of memory after only a few hours of uptime.

**Comment by klemsFR** [comment]
Confirming this issue with MDM 2.0.7.

**Comment by grebesche** [comment]
Same issue here (MDM 2.0.7)

**Comment by Semmu** [comment]
Same here. MDM 2.0.7, Linux Mint 17.3, MATE 1.12.0

**Comment by klemsFR** [comment]
Well, updated to mint 18 with mdm 2.0.10, no memory leak so far, uptime 18 days...

**Comment by danheidel** [comment]
Seeing this issue with Mint 18 Cinnamon, MDM 2.0.10.  MDM memory usage regularly goes up over 4GB.  Never had these issues in Mint 16 or 17.

**Comment by klemsFR** [comment]
Do you use mplayer? since i use mpv and mint 18 instead of mplayer and mint 17 i does not saw this leak.

**Comment by squirrl** [comment]
Seeing this issue with MDM 2.0.17 with Mint 18.1 running under VirtualBox 5.1.16. Over 4 GB ram usage after leaving my VM on for a number of days.

**Comment by cmrdt** [comment]
never happened before and then suddenly this, uses up almost all ram&swap >15GB!
uptime only few hours ago!!`

**Comment by xenopeek** [comment]
This may likely be specific to the theme used. Anyone still experiencing this issue please share your Linux Mint version, your MDM version and which theme you have configured in Login Window.

If you don't know your Linux Mint version you can run `inxi -S` on the terminal. If you don't know your MDM version run `mdm --version` on the terminal.

**Comment by xenopeek** [comment]
As there were no further updates I'm closing this issue.
