### ISSUE TITLE
A question: modify the windows behaviour

### ISSUE THREAD

**Issue by luca-vercelli** [linuxmint/mdm#136]
Dear all,
I have some questions, and I don't know if they are connected with MDM or not. I would like to modify some behaviours of the (Linux Mint) windows. For example, I would like:
* change the aspect of the titlebars, 
* change the position of the "close button",
* change the behaviour of the "scroll" button when it lies on the titlebar,
* create thumbnails of windows
* simulate mouse clicks on the screen, without any real click from user

What programs control such things? MDM? X?
Thank you in advance.

**Comment by monsta** [comment]
Please ask support questions at the [forums](http://forums.linuxmint.com), bug tracker is for reporting bugs.
