### ISSUE TITLE
Auto login as root

### ISSUE THREAD

**Issue by abda11ah** [linuxmint/mdm#137]
Hi,

I tried to enable autologin as root user but it doesn't works.
My version : Linuxmint 17.1 MATE / mdm_1.8.3+rebecca_amd64

**Comment by glebihan** [comment]
Logging in as root in a desktop environment is already an awful idea by itself.
Making it automatic is ... sorry, can't find polite words to describe it.

The configuration tool doesn't offer it, for a good reason.

**Comment by VarunAgw** [comment]
It is not that awful idea. It saves from a lot of annoyance esp. if are you Linux it in VM.

**Comment by caoruidong** [comment]
I think it is very necessary,for example,GUI auto testing and so on.

**Comment by mathieu-aubin** [comment]
I must say i agree that the user should have the final say... you could even have a **nice big poster with all your impolite words** explaining why *you* think it's not a good idea (for the life of me, i can't see anything even remotely ressembling to some sort of justification as to why you think that way)

Reminds me of the typical "Cuz, just cuz." answer.

I myself am using this mint box for testing purposes and it reboots alot hence my need to autologin a **root** (yes, that devil) 

If anyone has an answer i'd appreciate. Thanks

**Comment by VarunAgw** [comment]
@mathieu-aubin I'm using `nodm` these days. It is pretty good. You can check others too.
