### ISSUE TITLE
Enable numlock no longer possible

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mdm#138]
As i use a password with numbers in it, when i come to the login screen i like using the numberpad to enter in the numbers, but unfortunately i must first enable numlock before being able to do this. In previous version, i was able to check this option in the login window preferences under the options tab, but this option is no longer available.

**Comment by clefebvre** [comment]
The option is still there, it becomes available when you install the numlockx package.

The presence of this package create issues on some hardware so we could have it installed by default.

**Comment by philipzae** [comment]
Would be nice if the option was still visible and disabled, and gave a tooltip that numlockx needs to be installed in order to activate it.
