### ISSUE TITLE
Security issue: Password leakage. 

### ISSUE THREAD

**Issue by plutocrat** [linuxmint/mdm#139]
I'm using Mint 17.1 with the default Mint-X login screen. I have more than one account on my computer. On booting up the computer, the last used login is selected, and the cursor is in the password field. So far so good. 
If I mistype the password and press return, the red error message about incorrect credentials comes up. However, now the focus has moved away from the password field, and away from both of the existing accounts, so that if you retype the password it appears in large type on the screen as a new Login Name. 
Clearly this is a security issue if other people are in the room. 
My suggestion would be to retain focus in the password box, and require the user to manually select a different Login name.

**Comment by EddardStark** [comment]
Alongside being a security issue, this behaviour is extremely annoying. I second this suggestion.

**Comment by plutocrat** [comment]
The workaround is to use another login screen. I set mine to MDModern, which doesn't exhibit this behaviour
