### ISSUE TITLE
Live-System: The Display Manager ignores the setting in /etc/default/locale

### ISSUE THREAD

**Issue by DeVIL-I386** [linuxmint/mdm#141]
OS: LMDE 2
MDM: 1.8.3

The display manager ignored in the live system setting from /etc/default/locale
locale = LANG=de_DE.UTF-8

In the live system login screen remains in English.
After login, the system is loaded in the language that is specify in the file.
All graphical programs that starts with root rights, run in English.

In the permanently installed system, this problem does not occur.

If the live system LightDM is used, there are no problems.

**Comment by clefebvre** [comment]
Shouldn't it just auto-login the "mint" user anyway?

**Comment by DeVIL-I386** [comment]
It is the localized version of the ISO for German speaking users.

It's nice that all the language files are already present on the DVD, but provides the live system but an English menu.
To circumvent this limitation, the localized version was created.

https://sourceforge.net/projects/linuxmintdeutsch/files/lmde/

**Comment by DeVIL-I386** [comment]
Sorry, false alarm.

The culprit is not MDM, but the package live-config.
The script "/lib/live/config/0050-locales" overwrites the entry in "/etc/dafault/locale".
