### ISSUE TITLE
After switching user and logging in back, DE's lock screen is shown for 1-2 seconds

### ISSUE THREAD

**Issue by monsta** [linuxmint/mdm#142]
Steps to reproduce:

1. Have Mint 17.x or LMDE 2 Betsy installation. Note that if your Betsy is with MATE, you'll need to have mate-screensaver from Betsy repos, not from Jessie ones (so logind support would be disabled).
2. Invoke logout dialog and press "switch user" button.
3. Log in back via MDM greeter screen that shows up.
4. See your DE's lock screen popping up for 1-2 seconds. Then it goes away and you get into your DE.

This doesn't happen with LightDM, so it must be MDM issue.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mdm/commit/24e9222d702640751dc0a73b28dd4fdabbb0d996
