### ISSUE TITLE
Initial login screen size wrong on external 4K display

### ISSUE THREAD

**Issue by urbancamo** [linuxmint/mdm#146]
If I boot my Thinkpad X220 with the lid closed and an external 4K monitor connected then the initial mdm login screen is the size of the laptop display 1366x768 rather than the resolution of the external monitor 3840x2160. The X-Server is running at the right resolution so the effect you get is a small login page displayed at the top left.

Upon entering a password KDE boots correctly with the Linux Mint Logo displayed full screen, then the KDE desktop is also full screen.

**Comment by clefebvre** [comment]
Hi,

Please have a look at http://segfault.linuxmint.com/2015/08/configuring-the-mdm-login-screen-for-multiple-monitors/ for the resolution.

If it's to do with hidpi, also check the output of /usr/bin/mdm-get-monitor-scale.

Last but not least, check the output of https://raw.githubusercontent.com/linuxmint/mdm/master/files/usr/bin/mdm-get-monitor-scale as it was recently improved. (don't overwite your own /usr/bin/mdm-get-monitor-scale... as that wouldn't be compatible with your version of MDM.. if you want to do that, please make sure to recompile mdm using the git master version).
