### ISSUE TITLE
mdm ignores DefaultSession

### ISSUE THREAD

**Issue by jamincollins** [linuxmint/mdm#147]
I've tried for a while now to preconfigure the preferred default session for new users.  I've tried setting the following in the various mdm configs[1][2][3]:

```
[daemon]
DefaultSession=xfce.desktop
SessionDesktopDir=/usr/share/mdm/BuiltInSessions/:/usr/share/xsessions
```

While the xfce.desktop file exists (/usr/share/xsessions/xfce.desktop) and is listed in mdm's list of available session choices it is not the default for users that have not previously selected a session.

I've had to fall back to precreating a ~/.dmrc file for the users.  According to the commented mdm config the above should work.

```
# This is a directory where .desktop files describing the sessions live.  It is
# really a PATH style variable since 2.4.4.2 to allow actual interoperability
# with KDM.  Note that <dmconfdir>/Sessions is there for backwards
# compatibility reasons with 2.4.4.x.
#SessionDesktopDir=/etc/X11/sessions/:/etc/dm/Sessions/:/usr/share/mdm/BuiltInSessions/:/usr/share/xsessions/
# This is the default .desktop session.  One of the ones in SessionDesktopDir
#DefaultSession=gnome.desktop
```

[1] - /etc/mdm/custom.conf
[2] - /usr/share/mdm/distro.conf
[3] - /usr/share/mdm/defaults.conf

**Comment by jamincollins** [comment]
Any update?  It's been several months since this was reported.

**Comment by philer** [comment]
Just asking, have you tried setting the default session via GUI? Run mdmsetup to get there or find it somewhere in the depths of the menu. It has an option for default session. Not sure if that just writes to the config files you've been editing or does something more.

**Comment by jamincollins** [comment]
The intent is to automate the configuration for use during system builds.  As such, using the GUI is not an option, but I can certainly give it a shot to:
1) see if the GUI setting is respected
2) if so, find what additional bits it sets
