### ISSUE TITLE
Russian (unicode) password

### ISSUE THREAD

**Issue by CyberTailor** [linuxmint/mdm#149]
**Version:** MDM 2.0.4
**OS:** Linux Mint 17.2 MATE

How to toggle between Russian and English layouts?

**Comment by clefebvre** [comment]
You can set /etc/default/keyboard.

For instance, if you set your layout to "ru,gb" for instance, and options to "grp:alt_shift_toggle", you should be able to toggle between Russian and British using ALT+Shift.

This should work with current versions of MDM.

We enforced this for Logitech keyboard today with this commit: 

https://github.com/linuxmint/mdm/commit/a293167340624021e1b379118a647a97da9dd550
