### ISSUE TITLE
MDM doesn’t support big size images (336kb for example)

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mdm#150]
Don't know exact deadline size, the fact is in image size
Of Course I'm talking about profile pics

**Comment by Yanpas** [comment]
I am using pure gtk

**Comment by xenopeek** [comment]
This appears to have been solved at some point in time. I could set a 4.5 MB JPEG image as profile image on Linux Mint 18.1 Cinnamon with Mint-X HTML theme and MDM displays it fine.
