### ISSUE TITLE
Fingerprint authentication is not supported on the login screen.

### ISSUE THREAD

**Issue by johanbrandhorst** [linuxmint/mdm#152]
It is supported in both lightdm and gdm, is this support planned?

**Comment by bitboy85** [comment]
+1

**Comment by bitboy85** [comment]
The author of fingerprint gui published a fix: http://home.ullrich-online.cc/fingerprint/Forum/topic.php?TopicId=485&Posts=7

**Comment by marsjaninzmarsa** [comment]
Umm, worksforme. Since long time, like 2 years?
