### ISSUE TITLE
MDM Caps lock warning sign not updating intuitively

### ISSUE THREAD

**Issue by LinkTree3** [linuxmint/mdm#157]
Hi, I haven't found a discussion about this issue anywhere on the internet. Why is every HTML5 theme not removing the caps lock warning sign when caps lock is off? You have to manually click outside of the input box for it to realize caps lock is off and update the display... This is very confusing for new users. I assume that's some internal functionality and it's not yet exposed to the HTML+JS API and that's why all these HTML5 themes have the same issue.

**Comment by xenopeek** [comment]
Same issue as #120.
