### ISSUE TITLE
segfault in mdmgreeter while changing session to MATE

### ISSUE THREAD

**Issue by rpremuz** [linuxmint/mdm#159]
The system has **Linux Mint 17.2 x64 with Cinnamon 2.6.13**. Also **MATE 1.10.2** was installed through mint-meta-mate package.

In mdmsetup (Login Window Preferences) the following is selected:
Default session: Cinnamon
Theme: Simple UserList

```
$ uname -a
Linux mypc 3.16.0-39-generic #53~14.04.1-Ubuntu SMP Wed May 27 10:03:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ inxi -x -G
Graphics:  Card: NVIDIA GT218 [GeForce 210] bus-ID: 01:00.0 
           X.Org: 1.15.1 drivers: nvidia (unloaded: fbdev,vesa,nouveau) Resolution: 1920x1200@60.0hz 
           GLX Renderer: GeForce 210/PCIe/SSE2 GLX Version: 3.3.0 NVIDIA 340.93 Direct Rendering: Yes

$ dpkg -l | grep mdm
ii  mdm                   2.0.4+rafaela  amd64  MDM Display Manager
ii  mint-mdm-themes       2014.10.29     all    Linux Mint MDM Themes
ii  mint-mdm-themes-gdm   1.8.1          all    Linux Mint MDM Themes
ii  mint-mdm-themes-html  2.0.3          all    Linux Mint MDM Theme
```

I noticed the following issue: if a user tries to change the session to MATE on the login window, the login window disappears and the user is left with blank screen in background colour.

The syslog shows that there was a segfault in mdmgreeter at the moment when the user tried to switch the session type:

mdmgreeter[1967]: segfault at 7ffcbc000000 ip 00007f327bb30e2c sp 00007ffcbe4d65b8 error 4 in libc-2.19.so[7f327baae000+1bb000]

After some testing I'd say that the issue exist only if the login window has a GDM theme (the visual appearance of the issue for all the themes is the same but the segfault does not occur always). If the login window has a HTML theme or the GTK theme, the issue does not occur.

[Here](https://drive.google.com/drive/folders/0B2V313X0LzmQc1JocV9hcmVWOVE) I uploaded the following files:
syslog entries regarding mdm, mdmgreeter and cinnamon (with debugging enabled in /etc/mdm/mdm.conf)
crash report (from /var/crash)
/usr/share/mdm/defaults.conf
/usr/share/mdm/distro.conf
/etc/mdm/mdm.conf

**Comment by joamuran** [comment]
I have the same problem in similar circumstances. I'm using ubuntu Trusty (32 bit) with mate-desktop running. When I try to change marco window manager by muffin with:

```
muffin --replace
```
It runs fine and after some seconds it crashes with a segmentation fault.

Syslog error is this:

```
Dec  2 20:42:35 Toshi kernel: [ 3794.203892] muffin[6830]: segfault at 2c7 ip b7476797 sp bf9a0458 error 4 in libc-2.19.so[b733a000+1a8000]
```

My graphics card is an nvidia too:
```
$ inxi -x -G
Graphics:  Card: NVIDIA GT218M [GeForce 315M] bus-ID: 01:00.0 
           X.Org: 1.15.1 driver: nvidia Resolution: 1366x768@60.0hz, 1920x1080@59.9hz 
           GLX Renderer: GeForce 315M/PCIe/SSE2 GLX Version: 3.3.0 NVIDIA 340.96 Direct Rendering: Yes
```

And i'm using these versions of packages:
 ```
$ dpkg -l | grep muffin
ii  gir1.2-muffin-3.0                                           2.8.4-20151202003004-trusty                                     i386         GObject introspection data for Muffin
ii  libmuffin0                                                  2.8.4-20151202003004-trusty                                     i386         window and compositing manager (shared library)
ii  muffin                                                      2.8.4-20151202003004-trusty                                     i386         window and compositing manager
ii  muffin-common                                               2.8.4-20151202003004-trusty                                     all          window and compositing manager (data files)

$ dpkg -l | grep cinnamon
ii  cinnamon-desktop-data                                       2.8.0-20151202000604-trusty                                     all          Common files for Cinnamon desktop apps
ii  gir1.2-cinnamondesktop-3.0                                  2.8.0-20151202000604-trusty                                     i386         Introspection data for CinnamonDesktop
ii  libcinnamon-desktop4:i386                                   2.8.0-20151202000604-trusty                                     i386         Cinnamon library for loading .desktop files


$ dpkg -l | grep libc6
ii  libc6:i386                                                  2.19-0ubuntu6.6                                                 i386         Embedded GNU C Library: Shared libraries
ii  libc6-dbg:i386                                              2.19-0ubuntu6.6                                                 i386         Embedded GNU C Library: detached debugging symbols
ii  libc6-dev:i386                                              2.19-0ubuntu6.6                                                 i386         Embedded GNU C Library: Development Libraries and Header Files

```

**Comment by rpremuz** [comment]
This issue is also present on **Linux Mint 17.3 Rosa 64-bit with Cinnamon 2.8.6 and MATE 1.12.0**.

The syslog shows that there was a segfault in **mdmgreeter** at the moment when the user tried to switch the session type:
```
kernel: [  163.667274] mdmgreeter[2988]: segfault at 7fff84000000 ip 00007f2fa231ee2c sp 00007fff85d56488 error 4 in libc-2.19.so[7f2fa229c000+1bb000]
```
Here are the versions of mdm packages:
```
$ dpkg -l | grep mdm
ii  mdm                   2.0.7+rosa  amd64  MDM Display Manager
ii  mint-mdm-themes       2014.10.29  all    Linux Mint MDM Themes
ii  mint-mdm-themes-gdm   1.8.1       all    Linux Mint MDM Themes
ii  mint-mdm-themes-html  2.0.6       all    Linux Mint MDM Themes
```

**Comment by LinuxOnTheDesktop** [comment]
I have just encountered this, I think, on Mint Cinnamon 20.3. (I saw no ill-effect, but I have a Conky that displays errors of this type - and I would rather that that facility did not cry wolf.)

**Comment by JosephMcc** [comment]
I'd like to point out this is pretty much a dead project. As far as I know we know longer even ship the mint packages for it in Mint.
