### ISSUE TITLE
Feature Request: MDM-locker

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mdm#160]
Locker (aka ScreenSaver) needs better integration with MDM, currently LM ships 4 different DEs, in every DE there are various lockers. For example, XFCE is shipped with **ugly** xscreensaver, which requests password twicely (You click "Switch user", then you click user, who was already loginned, enter PW, and xscreesaver asks to type password again). LightDM+LightDM-locker do cooperate better (when you lock session - you are moved to logind screen), look fancy (they use GTK). Providing smth like lightdm-locker would be nice.

PS: I suggest to switch from xscreensaver to gnome-screensaver by 17.3 for XFCE. 
gnome-screensaver:
**+** Does not require gnome dependencies
**+** Looks nice (uses GTK theme), support background images via dconf
**+** Supports keyboard layout indicator
**-** Does not support screensavers

**Comment by JosephMcc** [comment]
> - Does not support screensavers

Probably a bad idea. People would not be happy. Cinnamon users complained about this forever until xscreensaver support was finally added.
