### ISSUE TITLE
Tab and arrow keys do not work on login screen

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mdm#163]
. . at least when using the ('pure') GTK login screen. Hence a natural way to navigate between users (to determine which user is to be logged on) is unavailable.

**Comment by ACinnamonUserInUK** [comment]
Just now I reencountered this problem. I find that <tab> does very strange things. Sometimes it seems to be taken to be an attempt at a password. At other times, pressing that key seemed to leave nothing - no user, no password field - selected.

**Comment by xenopeek** [comment]
Depends on the theme used whether it supports keyboard navigation.

**Comment by CottonEaster** [comment]
@xenopeek Oh. Is the theme at issue the 'window control' theme? Also, do the inbuilt Mint themes support keyboard navigation, please?

**Comment by xenopeek** [comment]
The theme you select in Login Window. It looks like the HTML themes generally support keyboard navigation best.

**Comment by CottonEaster** [comment]
I do not know which of the themes are HTML. It seems to me that it would be good were all of Mint's inbuilt themes (and whether those themes are HTML or not) to support keyboard navigation.

**Comment by xenopeek** [comment]
After the name of each theme in Login Window it displays in grey superscript whether it is a GTK, HTML or GDM theme. The HTML themes are the new feature of MDM (as compared to GDM 2.x from which it was forked)

**Comment by CottonEaster** [comment]
In my Settings -> Login Window -> I see no suffixes. I tried changing my 'controls' and 'windows borders' themes, in case they were stopping me from seeing the grey suffix about, er, theme information, but that change made no difference.

**Comment by CottonEaster** [comment]
Screenshots:

![image](https://user-images.githubusercontent.com/9998846/35486179-479d47f6-0462-11e8-9df6-034994067987.png)

![image](https://user-images.githubusercontent.com/9998846/35486189-64eb0e4c-0462-11e8-98f1-18f863f73cab.png)

**Comment by xenopeek** [comment]
That's not for MDM. That's for LightDM. Linux Mint 18.1 was the last release to use MDM by default. Newer releases use LightDM with Linux Mint's Slick Greeter, though MDM remains available (for users that upgraded in place from an earlier release).

**Comment by CottonEaster** [comment]
Oh.

I've just tested on _LightDM_ and the arrow keys do work. So that's good!
