### ISSUE TITLE
When shutting down or rebooting computer, I should be warned if I'm closing another user X session

### ISSUE THREAD

**Issue by hiboudev** [linuxmint/mdm#165]
#### Use case:

The computer is used by 2 users, each one having its own account.
User A is on the computer and User B needs it for 5 minutes, so User A switches user _without to log out from its own session_.
User B log in, do something for 5 minutes then accidentally shut down the computer instead of just logging out.
In result of this little and common mistake, _User A session was abruptly closed, with all its opened applications_.
#### Expected:

User B should at least see a window popup explaining what he is doing and that it would be better to just log out, with a button displayed in the popup itself. If he is really sure and have the permissions, of course he can continue shutting down (or rebooting) the computer (if possible with a hard-to-click button! :-).

**Comment by xenopeek** [comment]
Many thanks for contributing to MDM. We would welcome a PR to improve the shutdown dialog but as this issue isn't preventing MDM from working and Linux Mint has moved to use LightDM I'm closing this issue for now.
