### ISSUE TITLE
DisallowTCP=false not working in Linux Mint 17.3 Rosa

### ISSUE THREAD

**Issue by renatosilvagaio** [linuxmint/mdm#166]
I inserted the setting in /etc/mdm/mdm.conf:
[security]
DisallowTCP=false

Rebooted and the setting has no effect.
In a chroot environment i canno't export DISPLAY...

**Comment by joel-pinho** [comment]
I have the same problem with a Mint 17.3 fresh installation.
With the previous Mint 17.1 worked fine.

Any clue to solve it?
Thanks

**Comment by bzero** [comment]
this works for me:

[security]
DisallowTCP=false
[server-Standard]
command=/usr/bin/X -listen tcp -audit 0
