### ISSUE TITLE
Suggestion to Improve "Startup Application" Dialogue

### ISSUE THREAD

**Issue by RadicalRadish** [linuxmint/mdm#169]
System Details:
Linux Kernel 3.16.0-38-generic
Linux Mint 17.2 x64 Cinnamon - Rafaela
Cinnamon 2.6.13
Nemo 2.6.7

If I want to setup programs to run on startup of the system then I can use the "Startup Applications" program to reach dialogues that allow the user to do this. So I click on the add button and select "Custom Command". A dialogue then opens where the user can enter details of the command they wish to execute. This dialogue can be resized horizontally - which is actually a very useful function. However, if the dialogue is expanded horizontally nothing of any actual use to the user happens. In particular the text-box to enter the command stays the same size only the 'gray-area' to the right of the text-box expands. As commands can sometimes be quite long it would be much better if, on a horizontal resize, the text-boxes for Name, Command and Comment got longer - this is actually useful to the user.

In case I'm not being clear what I'm talking about here is a screenshot of what actually happens when the dialogue is expanded horizontally:

![small text-box](https://cloud.githubusercontent.com/assets/15947700/12985125/df48a550-d0e8-11e5-867d-30208a3ce74c.png)

Things would be much better if the text-boxes expanded not the grey-area to the right of the text-boxes.

Hope this suggestion is of help.

**Comment by JosephMcc** [comment]
This is actually a Cinnamon issue. I already created a PR to fix this so I'm going to close since it doesn't really belong here.
