### ISSUE TITLE
MDM @ LMDE2: cannot remove the "suspend"  button 

### ISSUE THREAD

**Issue by mabod** [linuxmint/mdm#170]
Since suspend is not reliably working on some PCs I wanted to remove the supend button completely. 

I found advice here:  https://github.com/linuxmint/mdm/blob/master/config/mdm.conf.in
But it is not working. Removing SUSPEND from SystemCommandsInMenu like

> SystemCommandsInMenu=HALT;REBOOT
> in
> /etc/mdm/mdm.conf

Does not make a difference.

**Comment by philer** [comment]
It may depend on the theme you're using. At least in the webkit greeter MDM tells the theme to hide the buttons. If the theme ignores that the buttons may still show up (though I'm not sure if MDM will ignore them).
