### ISSUE TITLE
Wishlist: login+savescreen

### ISSUE THREAD

**Issue by luca-vercelli** [linuxmint/mdm#171]
Currently, in mdm-setup I see 2 options for automatic login:
-Enable automatic login
-Enable temporized login

I think a third option would be great, mainly for business PC's:
-Enable automatic login + savescreen

This should enable automatic login, however, when session is up, it should be locked by means of savescreen.

Tell me if I am missing something, and if this can already be obtained in some way.

**Comment by hanzo2001** [comment]
In my case, the MATE / ScreenSaver project is in charge of locking the session and prompting for a password afterwards. Other flavors also use their own ScreenSaver.

Try using the ScreenSaver configuration to enable the lockout feature

**Comment by xenopeek** [comment]
Related to #168.
