### ISSUE TITLE
Login screen background cannot be set (always a black background)

### ISSUE THREAD

**Issue by Favorablestream** [linuxmint/mdm#174]
Hello,

Trying to set a login screen background in mdmsetup to a local image results in the background being a solid black.

Additionally the gear button to preview the screen displays an entirely black window.

I am running Mint 17.3 Cinnamon, and mdm 2.0.7.

mdmsetup window:
![mdmsetup](https://cloud.githubusercontent.com/assets/16925791/15807797/841b271a-2b34-11e6-9688-f91506911020.png)

Preview window:
![previewwindow](https://cloud.githubusercontent.com/assets/16925791/15807845/aa1536c6-2b35-11e6-993e-910bf34f23bd.png)

Login window:
![loginwindow](https://cloud.githubusercontent.com/assets/16925791/15807846/ad7f1160-2b35-11e6-8ad6-99a125f4dab2.jpg)

**Comment by philer** [comment]
Most likely a permissions issue. Make sure that MDM is allowed to read and enter every directory in the path to the image file you specified.

**Comment by Favorablestream** [comment]
Looks like my Google Drive client is messing with the permissions for that directory so I moved the image to another for now and it mostly works.

The strange thing is the background image displays on other monitors but no the primary display with the login dialog (which is still a black screen).

Is that the intended behaviour?

Thanks

**Comment by calexil** [comment]
Close if solved
