### ISSUE TITLE
mdm ignores automatic-ubiquity boot parameter

### ISSUE THREAD

**Issue by tylerecouture** [linuxmint/mdm#175]
It appears that mdm is the barrier by preventing the [automatic-ubiquity](https://wiki.ubuntu.com/UbiquityAutomation) boot parameter from running properly.

Example topics from the Mint forums etc:
https://forums.linuxmint.com/viewtopic.php?f=46&t=104511
https://github.com/morph027/preseed-linuxmint/issues/1#issuecomment-223901921
https://forums.linuxmint.com/viewtopic.php?f=46&t=169454

I would like to use Linux Mint as the OS for my high school computer lab(s), however without the ability for unattended install and preseed files, this isn't feasible.

**Comment by clefebvre** [comment]
Hi,

I'd be happy to fix it, but I'm not sure where/why it fails? Why do you think MDM is the cause of this?

**Comment by tylerecouture** [comment]
I'm fairly new to Linux (<1 year) so I don't really know what I'm talking about, but I've been trying REALLY hard to get an unattended install of Mint, and it appears that no one on the Internet has been able to do this since Mint 12.

Why do I think MDM is involved? The evidence is circumstantial:
1. [This user](https://forums.linuxmint.com/viewtopic.php?f=46&t=104511)'s preseeded install stopped working with Mint 13, when MDM was introduced
2. After installing LightDM on his installation ISO, it began working again

That's all I got.  If there's anything else I could test or try with my limited knowledge I'd love to try it.

**Comment by tylerecouture** [comment]
Actually, in all of my attempts it seems more likely that it just doesn't recognize preseed files (though perhaps they are related/same issue)
