### ISSUE TITLE
MDM Primary monitor not selectable in Login Window Preferences

### ISSUE THREAD

**Issue by trebushet** [linuxmint/mdm#176]
After installing Mint 18 (Cinnamon, fresh install),  primary monitor is not selectable. Nothing shows in the dropdown box. This worked fine in Mint 17.3

Graphics Card Nvidia GeForce GTX 760. Using proprietary drivers, but this did not work with nouveau  drivers either. 

I ran sudo nvidia-settings and saved the /etc/X11/xorg.conf which fixed the primary monitor of the login window at startup, but it's still not selectable in the  "Login Window Preferences"

Any ideas?

![selection_002](https://cloud.githubusercontent.com/assets/1671562/16546079/ee9234b8-4104-11e6-9d0a-3894911abe94.png)

**Comment by kimielski** [comment]
i also have the same issue..
inxi -Gx
`Graphics:  Card-1: Intel 2nd Generation Core Processor Family Integrated Graphics Controller bus-ID: 00:02.0`
           `Card-2: Advanced Micro Devices [AMD/ATI] Thames [Radeon HD 7550M/7570M/7650M] bus-ID: 01:00.0`
           `Display Server: X.Org 1.18.3 drivers: ati,radeon,intel (unloaded: fbdev,vesa)`
`Resolution: 1366x768@59.99hz, 1920x1200@59.95hz`
`GLX Renderer: Mesa DRI Intel Sandybridge Mobile GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes`

**Comment by calexil** [comment]
confirming same issue:

~ $ inxi -Gx
Graphics:  Card: Advanced Micro Devices [AMD/ATI] BeaverCreek [Radeon HD 6530D]
           bus-ID: 00:01.0
           Display Server: X.Org 1.18.3 driver: radeon
           Resolution: 1280x1024@60.02hz, 1680x1050@59.93hz
           GLX Renderer: Gallium 0.4 on AMD SUMO (DRM 2.43.0, LLVM 3.8.0)
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes

**Comment by ctrl-break** [comment]
I have the same problem. Mint 18 Cinnamon
```
$ inxi -Gx
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Oland XT [Radeon HD 8670 / R7 250/350]
           bus-ID: 01:00.0
           Display Server: X.Org 1.18.3 drivers: ati,radeon (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           GLX Renderer: Gallium 0.4 on AMD OLAND (DRM 2.43.0, LLVM 3.8.0)
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
```

**Comment by cmoud94** [comment]
Same issue here. Mint 18 Cinnamon.

```
$ inxi -Gx
Graphics:  Card-1: Intel 2nd Generation Core Processor Family Integrated Graphics Controller bus-ID: 00:02.0
           Card-2: NVIDIA GF108M [GeForce GT 540M] bus-ID: 01:00.0
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.00hz, 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Sandybridge Mobile GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
```

**Comment by m-ad** [comment]
Can confirm this, too. Mint 18 Mate.

    inxi -Gx
    Graphics:  Card: Advanced Micro Devices [AMD/ATI] Device 67df bus-ID: 01:00.0
               Display Server: X.Org 1.18.3 driver: amdgpu Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
               GLX Renderer: AMD Radeon RX 470 Graphics GLX Version: 4.5.13448 - CPC 16.30.3 Direct R

**Comment by dnel** [comment]
Also having this issue with a fresh Mint 18 Cinnamon install.

I use my laptop while docked with the laptop's built-in screen closed, however I am unable to do this as my 2 desktop monitors are blank until I log in.

Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller
           bus-ID: 00:02.0
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1280x1024@75.02hz, 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Ivybridge Mobile
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes

**Comment by tabakisp** [comment]
Also affected, Linux Mint 18 Xfce fresh install -option not even there. 

```
~ $ inxi -Gx
Graphics:  Card: Advanced Micro Devices [AMD/ATI] RV530/M56-P [Mobility Radeon X1600] bus-ID: 01:00.0
           Display Server: X.Org 1.18.3 drivers: ati,radeon (unloaded: fbdev,vesa) Resolution: 1920x1080@60.00hz
           GLX Renderer: Gallium 0.4 on ATI RV530 GLX Version: 2.1 Mesa 11.2.0 Direct Rendering: Yes
```

![screenshot_2016-10-06_15-11-40](https://cloud.githubusercontent.com/assets/7551798/19151987/66a69908-8bd8-11e6-9402-d0560b3658e5.png)
![screenshot_2016-10-06_15-22-50](https://cloud.githubusercontent.com/assets/7551798/19152060/c6daa29c-8bd8-11e6-8f4c-4bf9695d3582.png)

**Comment by anhzhang** [comment]
Encountered the same issue:
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah

$ inxi -Gx 
Graphics:  Card-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller bus-ID: 00:02.0
           Card-2: Advanced Micro Devices [AMD/ATI] Cedar [Radeon HD 5000/6000/7350/8350 Series] bus-ID: 01:00.0
           Display Server: X.Org 1.18.3 drivers: ati,radeon,intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           GLX Renderer: Gallium 0.4 on AMD CEDAR (DRM 2.43.0, LLVM 3.8.0)
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes

**Comment by clefebvre** [comment]
Hi,

Please paste the output of xrandr.

**Comment by clefebvre** [comment]
Please run the following code and paste the output:

```python
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk

screen = Gdk.Screen.get_default ();
mdm_wm_num_monitors = screen.get_n_monitors();

print("Number of monitors found: %d" % mdm_wm_num_monitors)

if (mdm_wm_num_monitors > 1):
    for i in range(0,mdm_wm_num_monitors):
        plugname = screen.get_monitor_plug_name (i);
        print plugname
```
If you're not sure how to do this, save it into a file called **monitors.py**, in your home folder directory.

Then run the following commands:

`cd`
`python ./monitors.py`

**Comment by clefebvre** [comment]
It's an adaptation in Python of what MDM does in C.

Here it gives me: 

> Number of monitors found: 2
> DP-1
> HDMI-0

**Comment by kimielski** [comment]
xrandr

> Screen 0: minimum 8 x 8, current 3286 x 1200, maximum 32767 x 32767
LVDS1 connected 1366x768+1920+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1366x768      59.99*+  40.00  
   1360x768      59.80    59.96  
   1280x720      60.00  
   1024x768      60.00  
   1024x576      60.00  
   960x540       60.00  
   800x600       60.32    56.25  
   864x486       60.00  
   640x480       59.94  
   720x405       60.00  
   680x384       60.00  
   640x360       60.00  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+
   1920x1080     60.00    50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x720      60.00    50.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   720x480i      60.00    59.94  
   640x480       60.00    59.94  
VGA1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
VGA-1-1 disconnected

python ./monitors.py

> Number of monitors found: 2
HDMI1
LVDS1

**Comment by calexil** [comment]
jd@jd-work ~ $ xrandr
Screen 0: minimum 320 x 200, current 2704 x 1280, maximum 8192 x 8192
HDMI-0 connected 1024x1280+0+0 left (normal left inverted right x axis y axis) 338mm x 270mm
   1280x1024     60.02*+  75.02  
   1152x864      75.00  
   1024x768      75.08    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32  
   640x480       75.00    72.81    60.00  
   720x400       70.08  
VGA-0 connected primary 1680x1050+1024+230 (normal left inverted right x axis y axis) 433mm x 271mm
   1680x1050     59.93*+
   1280x1024     75.02    60.02  
   1440x900      74.98    59.89  
   1024x768      75.08    70.07    60.00  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    60.00  
   720x400       70.08

**Comment by clefebvre** [comment]
Hmm... ok, so it's not down to that. I'll try and provide you with a version of mdmsetup which provides more traces then.

**Comment by clefebvre** [comment]
If anyone's happy with coding in C, the part of the code responsible for populating the combo box is at https://github.com/linuxmint/mdm/blob/master/gui/mdmsetup.c#L2579.

The way you build mdm is like other projects:

- Add source repositories in mintsources.
- apt update
- apt build-dep mdm
- apt install git dpkg-dev

then get the source code:

- git clone https://github.com/linuxmint/mdm/blob/master/gui/mdmsetup.c#L2579
- cd mdm

then compile

- dpkg-buildpackage

then install the .deb produced in the parent folder

You can then run "sudo mdmsetup".

**Comment by clefebvre** [comment]
If you are running a 64-bit version of Mint 18, then you try this version of mdmsetup.

```
cd
wget http://filebin.ca/30r9QQkl7QYc/mdmsetup
chmod a+rx ./mdmsetup
sudo ./mdmsetup
```

The output should tell us how many monitors are detected and what their plug names are.

Warning:

- Only run this if you're on a 64-bit version of Mint 18 (it probably works on Mint 17.x 64-bit but why take a risk).
- Make sure you understand what I'm asking you to do. You're basically downloading a binary from the Internet and running it as root here, you can't see its code, you don't know anything about it but whether or not you trust its source.

Once this is solved I'll remove the link, cause I don't trust filebin all that much myself.

**Comment by kimielski** [comment]
~ $ sudo ./mdmsetup
mdmsetup[15712]: Gtk-CRITICAL: IA__gtk_label_get_label: assertion 'GTK_IS_LABEL (label)' failed
mdmsetup[15712]: Gtk-CRITICAL: IA__gtk_label_set_use_markup: assertion 'GTK_IS_LABEL (label)' failed
mdmsetup[15712]: Gtk-CRITICAL: IA__gtk_label_set_label: assertion 'GTK_IS_LABEL (label)' failed
mdmsetup[15712]: Gtk-CRITICAL: IA__gtk_label_get_label: assertion 'GTK_IS_LABEL (label)' failed
mdmsetup[15712]: Gtk-CRITICAL: IA__gtk_label_set_use_markup: assertion 'GTK_IS_LABEL (label)' failed
mdmsetup[15712]: Gtk-CRITICAL: IA__gtk_label_set_label: assertion 'GTK_IS_LABEL (label)' failed
Number of monitors: 2
Monitor found in configuration: 'None'
Found plug name: '(null)'
Found plug name: '(null)'

**Comment by calexil** [comment]
mdmsetup[31989]: Gtk-CRITICAL: IA__gtk_label_set_use_markup: assertion 'GTK_IS_LABEL (label)' failed
mdmsetup[31989]: Gtk-CRITICAL: IA__gtk_label_set_label: assertion 'GTK_IS_LABEL (label)' failed
mdmsetup[31989]: Gtk-CRITICAL: IA__gtk_label_get_label: assertion 'GTK_IS_LABEL (label)' failed
mdmsetup[31989]: Gtk-CRITICAL: IA__gtk_label_set_use_markup: assertion 'GTK_IS_LABEL (label)' failed
mdmsetup[31989]: Gtk-CRITICAL: IA__gtk_label_set_label: assertion 'GTK_IS_LABEL (label)' failed

Number of monitors: 2
Monitor found in configuration: 'None'
Found plug name: '(null)'
Found plug name: '(null)'

**Comment by calexil** [comment]
@kimielski do you have two different plugs? I think this is an xrandr detection issue

**Comment by kimielski** [comment]
@calexil first is the notebook lcd, second hp monitor connected via hdmi

**Comment by calexil** [comment]
Okay, I'm gonna hunker down and really try to fix this over the weekend... I am tired of my login window being wrong and rotated

**Comment by clefebvre** [comment]
Ok, that's interesting... @kimielski 's results especially cause he ran both the python and the C version and I can see a difference in the results.

**Comment by clefebvre** [comment]
for the record, this is what the binary does:

```c
static void
setup_monitors (void)
{
	GtkWidget  *primary_monitor_combobox = glade_xml_get_widget (xml, "primary_monitor_combobox");
	GtkWidget  *primary_monitor_label = glade_xml_get_widget (xml, "primary_monitor_label");

	gtk_widget_set_sensitive (primary_monitor_combobox, TRUE);	
	
	GdkScreen *screen = gdk_screen_get_default ();
	int mdm_wm_num_monitors = gdk_screen_get_n_monitors (screen);	

	printf("Number of monitors: %d\n", mdm_wm_num_monitors);

	if (mdm_wm_num_monitors > 1) {
		gint active = 0;
		int i;
		gchar * org_val = mdm_config_get_string (MDM_KEY_PRIMARY_MONITOR);
		printf("Monitor found in configuration: '%s'\n", org_val);
		for (i = 0; i < mdm_wm_num_monitors; i++) {
			char * plugname = gdk_screen_get_monitor_plug_name (screen, i);		
			printf("Found plug name: '%s'\n", plugname);
			if (!ve_string_empty (plugname)) {			
				gtk_combo_box_append_text (GTK_COMBO_BOX (primary_monitor_combobox), plugname);
				monitors = g_list_prepend (monitors, plugname);
				printf("   added\n");
				if (strcmp(plugname, org_val) == 0) {
					active = i+1;				
					printf("   selected as active\n");
				}
			}		
		}
		if (active > 0) {		
			gtk_combo_box_set_active (GTK_COMBO_BOX (primary_monitor_combobox), active);
		}
		monitors = g_list_reverse (monitors);				
		g_object_set_data_full (G_OBJECT (primary_monitor_combobox), "key", g_strdup (MDM_KEY_PRIMARY_MONITOR), (GDestroyNotify) g_free);
		g_signal_connect (primary_monitor_combobox, "changed", G_CALLBACK (combobox_changed), NULL);	
		g_free (org_val);
	}
	else {
		gtk_widget_hide (primary_monitor_combobox);
		gtk_widget_hide (primary_monitor_label);
	}	
}
```

**Comment by calexil** [comment]
issue=plugname methinks, if the monitor is not labeled correctly nothing would show up

**Comment by calexil** [comment]
Im going to try and spoof the plug names and see if it fixes it... I don't really know how but ima try

**Comment by calexil** [comment]
Nov  4 17:34:05 jd-work mdm[2411]: mdm[2411]: DEBUG: mdm_socket_handler: Accepting new connection fd 7
Nov  4 17:34:05 jd-work mdm[2411]: DEBUG: mdm_socket_handler: Accepting new connection fd 7
Nov  4 17:34:05 jd-work mdm[2411]: mdm[2411]: DEBUG: Handling user message: 'GET_CONFIG greeter/PrimaryMonitor :0'
Nov  4 17:34:05 jd-work mdm[2411]: mdm[2411]: DEBUG: Handling GET_CONFIG: greeter/PrimaryMonitor for display :0
Nov  4 17:34:05 jd-work mdm[2411]: mdm[2411]: DEBUG: Looking up per display value for greeter/PrimaryMonitor
Nov  4 17:34:05 jd-work mdm[2411]: mdm[2411]: DEBUG: Requesting group=greeter key=PrimaryMonitor locale=(null)
Nov  4 17:34:05 jd-work mdm[2411]: mdm[2411]: DEBUG: Looking up key: greeter/PrimaryMonitor
Nov  4 17:34:05 jd-work mdm[2411]: mdm[2411]: DEBUG: Handling user message: 'CLOSE'
Nov  4 17:34:05 jd-work mdm[2411]: DEBUG: Handling user message: 'GET_CONFIG greeter/PrimaryMonitor :0'
Nov  4 17:34:05 jd-work mdm[2411]: DEBUG: Handling GET_CONFIG: greeter/PrimaryMonitor for display :0
Nov  4 17:34:05 jd-work mdm[2411]: DEBUG: Looking up per display value for greeter/PrimaryMonitor
Nov  4 17:34:05 jd-work mdm[2411]: DEBUG: Requesting group=greeter key=PrimaryMonitor locale=(null)
Nov  4 17:34:05 jd-work mdm[2411]: DEBUG: Looking up key: greeter/PrimaryMonitor
Nov  4 17:34:05 jd-work mdm[2411]: DEBUG: Handling user message: 'CLOSE'

**Comment by calexil** [comment]
getting closer

**Comment by calexil** [comment]
shouldn't there be a screen:0 and a screen:1 in xrandr?

**Comment by calexil** [comment]
@clefebvre where is the mdm.conf file stored?

**Comment by clefebvre** [comment]
in /etc/mdm/

**Comment by calexil** [comment]
thx

**Comment by clefebvre** [comment]
let's chat in #linuxmint-dev

**Comment by kimielski** [comment]
when i edit  /etc/mdm/Init/Default and add this:

hdmi1_connected=$(xrandr -q | grep "HDMI1 connected")
if [ -n "$hdmi1_connected" ]; then
xrandr --output HDMI1 --primary --mode 1920x1200 --pos 0x0 --rotate normal --output LVDS1 --off
fi

then after reboot - notebook screen is off, and HDMI monitor resolution in login screen is proper.
Primary monitor in Login window preferences is still empty.

**Comment by calexil** [comment]
@kimielski band-aid on bullet hole, but I might try that if clem and I can't sort it

**Comment by clefebvre** [comment]
Ok, it turns out it's a regression in GTK2. I'm working on a way to identify monitors by ID when the plug name isn't available.

**Comment by rarsa69** [comment]
For now, I identified the monitors with xrandr
`$ xrandr`
and then added this line at the end of /etc/mdm/Init/Default 
`xrandr --output VGA-0 --same-as HDMI-0`

Note that in your case the monitor names may be different. In my case xrandr detected
**VGA-0** connected 1680x1050+1920+0
**HDMI-0** connected primary 1920x1080+0+0

**Comment by SteveSmithCIS** [comment]
I've got same problem. Had it on Debian distro as well. 

xrandr output (seems to 'see' the monitor..)
[CODE]
Screen 0: minimum 320 x 200, current 1440 x 900, maximum 8192 x 8192
DVI-0 disconnected (normal left inverted right x axis y axis)
DVI-1 connected primary 1440x900+0+0 (normal left inverted right x axis y axis) 408mm x 255mm
   1440x900      59.89 +  74.98* 
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
[/CODE]

lspci | grep VGA
[CODE]
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] BeaverCreek [Radeon HD 6530D]
[/CODE]

I know it's an older machine/card, but I was looking this up to see if it worked better on Mint and found this thread. Something about the Radeon driver with Linux or ??
