### ISSUE TITLE
mdm[3449]: GLib-CRITICAL errors in syslog at startup/resume

### ISSUE THREAD

**Issue by ourichermath** [linuxmint/mdm#179]
From my syslog, it looks like these mdm errors happen at each startup.  I don't see anything like them here, so I thought I'd report them:

```
mdm[3449]: GLib-CRITICAL: g_key_file_get_string: assertion 'key_file != NULL' failed
mdm[3449]: GLib-CRITICAL: g_key_file_free: assertion 'key_file != NULL' failed
```

I don't know what the relationship is (if any), but those are always directly followed by:

```
dbus[2428]: [system] Activating via systemd: service name='org.freedesktop.ConsoleKit' unit='console-kit-daemon.service'
systemd[1]: Starting Console Manager...
console-kit-daemon[3639]: (process:3703): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
console-kit-daemon[3639]: missing action
dbus[2428]: [system] Successfully activated service 'org.freedesktop.ConsoleKit'
systemd[1]: Started Console Manager.
console-kit-daemon[3639]: (process:3712): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
org.a11y.Bus[3785]: Activating service name='org.a11y.atspi.Registry'
org.a11y.Bus[3785]: ** (process:3798): WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
```

```
apt show mdm
Package: mdm
Version: 2.0.10+sarah
```

This is on a recent (couple of days ago) clean install of Linux Mint 18 Cinnamon x64.

**Comment by ximex** [comment]
I got the same error in the logs. I used 17.3.
I have no taskbar and if i start the "cinnamon-control-center" there are many settings missing.
I tried to update to Linux Mint 18 but this didn't help or changed anything.

**Comment by ACinnamonUserInUK** [comment]
I have the same error in my log - on Mint 18.1 Cinnamon.

**Comment by mihai-mocanu** [comment]
+1

**Comment by rebelwocause** [comment]
MDM Errors in syslog on bootup

mdm[1183]: GLib-CRITICAL: g_key_file_get_string: assertion 'key_file != NULL' failed
mdm[1183]: GLib-CRITICAL: g_key_file_free: assertion 'key_file != NULL' failed

I have been running Mint 17.3, Mint 18.1 and LMDE2 (all up to date) and have always had these errors.

There may be a problem with Source Code in mdm-daemon-config.c as follows:
(Sorry for the line comments but could not figure the best way to make the
pasted code readable with markdown!)

//char *
//mdm_daemon_config_get_session_xserver_args (const char *session_name)
//{
//	char        *session_filename; //*** NEVER INITIALIZED??
//	const char  *path_str;
//	char       **search_dirs;
//	GKeyFile    *cfg;
//	static char *xserver_args;
//	static char *cached = NULL;
//	char        *ret;
//
//	cfg = NULL;
//
//	/* clear cache */
//	if (session_name == NULL) {
//		g_free (xserver_args);
//		xserver_args = NULL;
//		g_free (cached);
//		cached = NULL;
//		return NULL;
//	}
//
//	if (cached != NULL && strcmp (ve_sure_string (session_name), ve_sure_string (cached)) == 0)
//		return g_strdup (xserver_args);
//
//	g_free (xserver_args);
//	xserver_args = NULL;
//	g_free (cached);
//	cached = g_strdup (session_name);
//
//	path_str = mdm_daemon_config_get_value_string (MDM_KEY_SESSION_DESKTOP_DIR);
//	if (path_str == NULL) {
//		mdm_error ("No session desktop directories defined");
//		goto out;
//	}
//
//	search_dirs = g_strsplit (path_str, ":", -1);
//
////*** session_filename is uninitialized here so mdm_common_config_load_from_dirs will return NULL!?!?!?
////*** is this missing:		session_filename = mdm_ensure_extension (session_name, ".desktop");
//	cfg = mdm_common_config_load_from_dirs (session_filename,
//						(const char **)search_dirs,
//						NULL);
//	g_strfreev (search_dirs);
//
//	xserver_args = NULL;
////*** There is no check here if (cfg == NULL) ????
////*** This code would cause the exact errors that appear in syslog ????
//	mdm_common_config_get_string (cfg, "Desktop Entry/X-Mdm-XserverArgs", &xserver_args, NULL);
//
// out:
//
//	ret = g_strdup (xserver_args);
//
//	g_key_file_free (cfg);
//
//	return ret;
//}
//

**Comment by eduardochico** [comment]
+1

**Comment by xenopeek** [comment]
It's unclear to me if the original issue description from mid 2016 is related to the more recent questions about the code. If users are still affected by this issue I would suggest to take help from the forums for more in depth troubleshooting before reporting back here with information for the developers to work on. For more information see our troubleshooting guide https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/.

Linux Mint 18.2 switched to use LightDM with Slick Greeter. If you upgraded in place to Linux Mint 18.2 or 18.3, from an earlier Linux Mint version, you would still be using MDM unless you replaced it yourself. See the instructions on https://blog.linuxmint.com/?p=3306 for replacing MDM if you're affected by this MDM issue.
