### ISSUE TITLE
Mint 17.3 Cinnamon Trying to Use pam_kwallet

### ISSUE THREAD

**Issue by ourichermath** [linuxmint/mdm#180]
On every startup of Mint 17.3 Cinnamon x64, I get errors logged about kwallet.  This is Cinnamon and I assume kwallet is for KDE.  AFAIK, I have nothing of KDE installed.  Here are the relevant lines from auth.log:

```
mdm[1437]: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory

mdm[1437]: PAM adding faulty module: pam_kwallet.so
```

**Comment by f3l1x** [comment]
Same by me. Linux Mint 18 x64.

**Comment by philwalk** [comment]
Same symptoms exactly, Linux Mint 18 x64, nothing of KDE installed.

**Comment by ACinnamonUserInUK** [comment]
Same for me too - on Mint 18.1 x64 Cinnamon.

**Comment by jonabasque** [comment]
Some error, any solution?

**Comment by e178551** [comment]
/etc/pam.d/mdm 
place # whrer pam_kwallet 
or
open subl on /etc/pam.d/
search for pam_kwallet with shift+F
and comment it out

**Comment by CottonEaster** [comment]
@e178551 e178551: your instructions are not clear. Could you please clarify? For one thing, you could use code format

`like this`

or like `this`. Thanks.

**Comment by e178551** [comment]
there is to way to turn of the pam_kwallet
first is : 
sudo subl[or nano  or vim or code (depends on which editor you use)] /etc/pam.d/mdm
place '#' before where pam_kwallet is found (comment it or delete)
The second way is mostly for mint 18.3:
the principle is same but You have to find all the pam_kwallet and comment it out from in /etc/pam.d/ directory  u can use grep or subl with shift+F to find pam_kwallet and comment it out

**Comment by CottonEaster** [comment]
On my Mint 18.3 Cinnamon the file in question is `/etc/pam.d/lightdm`.
