### ISSUE TITLE
Do not adds link /etc/systemd/system/display-manager.service

### ISSUE THREAD

**Issue by vlad1777d** [linuxmint/mdm#186]
Hello.

I'm using Debian unstable x64 Cinnamon (from debian's repos), MDM from LMDE2's repos (because it's absent in debian's repos and developers refused to add MDM there).

After installing MDM package there was an error in terminal, after when I rebooted display manager do not launched.
I had to remove simulink /etc/systemd/system/display-manager.service, which pointed to /lib/systemd/system/lightdm.service, and create simulink /etc/systemd/system/display-manager.service, which pointed to /lib/systemd/system/mdm.service.

After that all worked greatly.
It would be greate if that link created with installing package or 'sudo dpkg-reconfigure mdm'.
Thank you.

Best regards,
Vladislav.

**Comment by ACinnamonUserInUK** [comment]
I have had a similar experience, but I suspect that what we have here is a bug. For my experience (
on Mint 18.1 x64 Cinnamon) was as follows.

On a system with mdm installed (and with no other login manager installed, though I had added one and the removed it), and _which is using systemd_ as its init manager,

`sudo dpkg-reconfigure mdm`

produced

`Upstart detected. Removing rc.d links.`

And upon restarting my system had terrible trouble booting and I had to restore from a backup.

**Comment by xenopeek** [comment]
Indeed dpkg-reconfigure mdm does not create the /etc/systemd/system/display-manager.service -> /lib/systemd/system/mdm.service symlink as we might expect.

As Linux Mint has moved to use LightDM and develop its Slick Greeter for that, as replacement for MDM, I guess the interest in seeing this feature request is past. Closing this issue for now.
