### ISSUE TITLE
Does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by viggy96** [linuxmint/mdm#192]
Booting with MDM enabled causes the system to boot into low-graphics mode, and reports that the screen and input device configurations have failed.

**Comment by clefebvre** [comment]
Are you using NVIDIA Prime?

**Comment by viggy96** [comment]
Yes, I have NVIDIA Optimus, through the native drivers, not Bumblebee.

**Comment by clefebvre** [comment]
OK that's normal. The Ubuntu version of ubuntu-drivers-common and nvidia-prime do not support MDM. Hopefully Alberto (who's maintaining these packages) will add these one day, but for now if you want to use Optimus in Ubuntu you need to switch to LightDM.
