### ISSUE TITLE
[BUG] Sometimes, the login password is being passed as a language option

### ISSUE THREAD

**Issue by ghost** [linuxmint/mdm#194]
A couple of days ago, i realized some programs would crash or not start at all. I read somewhere online that it may be due to an incorrect language so I checked it out. Imagine my shock when I discovered my login password was not only in plain text but set as the system language, which meant it was visible to any running program. This is a serious security flaw that needs to be fixed ASAP. I don't know if this is a race condition or the login screen inadvertently selecting the language box while I'm typing my password.

**Comment by clefebvre** [comment]
Can you provide steps to reproduce this issue?

**Comment by fu-sen** [comment]
This bug has also recently been reported on the Linux Mint Japan forum.
(I will be able to link concrete URL soon)

I also confirm that the language setting has recently changed to Cinnamon.
It may be related to this problem. Unfortunately this reproduction method can not be established now.
It may be related to somewhat package update.

In any case it can be improved by setting Language.

**Comment by fu-sen** [comment]
Bug report topic on Linux Mint Japan Forum (Japanese):
http://forums.linuxmint-jp.net/viewtopic.php?t=1741

**Comment by fu-sen** [comment]
topic on Linux Mint Forums:
https://forums.linuxmint.com/viewtopic.php?t=233956

**Comment by clefebvre** [comment]
Can you confirm the following information?

```
mdm --version
cat /etc/linuxmint/info
```

And last but not least, which MDM theme you are using?
