### ISSUE TITLE
New Mdm Themes

### ISSUE THREAD

**Issue by samsstuff** [linuxmint/mdm#195]
Hey Clem
Not sure if this is the right place to add this, I made a couple more themes if you want them, I'll be putting any new ones on github for you or anyone else to use from now on, got the canvas working good now by using phaser's html5 framework, it works nice with it.

If you want them you can get them here: https://github.com/samsstuff

Take care
Sam

**Comment by ACinnamonUserInUK** [comment]
We could use some new themes, I feel.
