### ISSUE TITLE
autologin doesn't work

### ISSUE THREAD

**Issue by danboid** [linuxmint/mdm#196]
I'm running mdm 2.0.17 under Linux Mint 18.1 MATE 32-bit and auto-login, when used without timed login, doesn't work.

The problem with having to enable timed login is that it adds at least another (unecessary) 10 seconds to the boot process. If I don't enabled timed login, I have to enter a password to login to X hence autologin is broke.

**Comment by danboid** [comment]
When I have auto-login enabled then I don't expect to see mdm at all during boot, only when I log out of X.

**Comment by Cos-mo** [comment]
A known problem since Mint 18.

**Comment by znlambov** [comment]
Same here, 18.1 64bit Cinnamon

**Comment by boorac** [comment]
Same here, would be great if this were resolved

**Comment by markpotts123** [comment]
How can something like this get broken!!! We use Mint in a kiosk solution where auto-login is critical. Timed login does not appear to work without keyboard input. As this is a touch-screen kiosk we don't have a keyboard. This effectively makes Mint 18 unusable for our application!!!

**Comment by N6REJ** [comment]
was this ever resolved?  Is there a work around?

**Comment by markpotts123** [comment]
I could not find a fix. According to several other threads it seems to be a timing interaction that can occur during boot/startup. Our work around was to revert to Mint 17.

**Comment by Cypher1** [comment]
Does anyone know if mdm can be disabled and replaced with another autologin script etc?
mdm is lovely to look at but I hate entering decryption passwords and login passwords at every boot.

**Comment by xenopeek** [comment]
Linux Mint 18.2 switched to use LightDM with Slick Greeter. If you upgraded in place to Linux Mint 18.2 or 18.3, from an earlier Linux Mint version, you would still be using MDM unless you replaced it yourself. See the instructions on https://blog.linuxmint.com/?p=3306 for replacing MDM if you're affected by this MDM issue. Auto login works best on Linux Mint 18.3 with LightDM.
