### ISSUE TITLE
Default Cinnamon login screen should look like the new lock screen

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/mdm#198]
It's inharmonious for the login screen and the lock screen to look so different. IMO, the default Cinnamon login screen should look like the new lock screen.

99% of the time users are logging in to the same account, they shouldn't have to click on their username or type their username every time to get to the password entry text box. Their usual account should be pre-selected and the password entry box should be on screen and in focus.

**Comment by JosephMcc** [comment]
The login screen has nothing to do with Cinnamon. It's also used in both the Mate and XFCE versions so the suggestion doesn't really make sense.
