### ISSUE TITLE
User can very easily enter their password when being prompted for username

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mdm#201]
After a failure authentication attempt, the user expects to have to re-enter their password. However, Mint is at this point prompting for a *username*. Thus the password can end up displayed in plain text on the screen.

I am confident that this problem was reported somewhere else, but for the life of me I can't find where.

One might respond: users should pay more attention. The response to _that_ is: it's understandable that in this instance they don't, and indeed a good workflow requires that various things be done on autopilot; also, surely we want to avoid this security problem and equally surely it would be easy to fix. For, to fix it, it would suffice to have a jiggling box, or flashing text - anything to make it more obtrusively evident that a username is now being asked for. Alternatively, or additionally: ask, first, for re-entry of the _password_.

**Comment by jounathaen** [comment]
This was changed, because Users (Me for instance :-D ) typed their password accidentally in the username field. So now, you can't enter a password without paying attention that you selected the right user.
But Indeed, the behavior could be changed, to act as you described.
I use the down key :arrow_down: to select my user again, for a quick re-entering after password fault.

**Comment by ACinnamonUserInUK** [comment]
Jounathaen, thanks for the response.

Your (main) point is that the way that the way logon worked previously, users displayed their passwords accidentally - yes? Well, that is what happens (in a slightly different way to previously, I take it) _now_! Moreover - and as I think you've indicated that you recognise - my aforementioned 'jiggling box, or flashing text' solution would not be (right?) a return to the previous problematic setup.

As to the ⬇️ key: it's good to be able to use that key, but I find <tab> more intuitive. Perhaps <tab> could be added.

**Comment by xenopeek** [comment]
It depends on the theme selected (in Login Window) how failed authentication is handled. Many themes will just prompt for the password again while other themes have a "if you entered username and password combination incorrectly, start over from the beginning" approach.

**Comment by CottonEaster** [comment]
Well, do all of Mint's in-built themes take the more secure of those two approaches? It seems they should, though I do not know whether they do.
