### ISSUE TITLE
Are there command-line tools to interact with mdm, like dm-tools?

### ISSUE THREAD

**Issue by jeenuv** [linuxmint/mdm#202]
I'm using i3 on my Mint installation. I wanted to be able to switch user and return to GDM et. al. I'm told that dm-tool helps with that on lightdm. I wanted to know if mdm has any of that, or if there are alternatives.

**Comment by koushik-ms** [comment]
have the same issue. wondering if a solution exists...

**Comment by xenopeek** [comment]
I don't think so. Linux Mint 18.1 was the last release that used MDM; subsequent releases use LightDM with our Slick Greeter, though MDM remains available for systems that have been upgraded in place.
