### ISSUE TITLE
Possible redundant localized .desktop files

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mdm#206]
On GitHub, the gui/ folder contains the following:  
- both `mdmflexiserver.desktop` and `mdmflexiserver.desktop.in`
- both `mdmsetup.desktop` and `mdmsetup.desktop.in.in`

In each case, maybe the file without .in isn't needed, since it's generated automatically during build?

**Comment by xenopeek** [comment]
Many thanks for contributing to MDM. As this issue isn't preventing MDM from working and Linux Mint has moved to use LightDM and Linux Mint's Slick Greeter, I'm closing this issue for now.
