### ISSUE TITLE
Please consider updating MDM to libwebkitgtk-3.0-0

### ISSUE THREAD

**Issue by System25** [linuxmint/mdm#207]
Hi, I'm preparing a Linux Mint small Linux distribution and I'm trying to make it fit in a CD-ROM.
I listed deb installed packages by size with the following command:
  `dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n`

That gave the following output:
```
25492	mint-mdm-themes-html
30087	libwebkitgtk-1.0-0
30087	libwebkitgtk-3.0-0
30156	libicu55
39399	linux-image-4.4.0-36-generic
40380	libwebkit2gtk-4.0-37
44300	libllvm3.8
68662	linux-headers-4.4.0-36
114597	libgl1-mesa-dri
115167	mint-x-icons
117316	linux-image-extra-4.4.0-36-generic
121492	linux-firmware

```
So I noticed that there are two versions of libwebkitgtk (libwebkitgtk-1.0-0 and libwebkitgtk-3.0-0). And if I try to remove libwebkitgtk-1.0-0 the only dependence is MDM:

```
$ sudo apt-get remove libwebkitgtk-1.0-0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gir1.2-javascriptcoregtk-3.0 gir1.2-webkit-3.0 libart-2.0-2 libdmx1 libgail18 libgnomecanvas2-0 libgnomecanvas2-common libjavascriptcoregtk-1.0-0 libjavascriptcoregtk-3.0-0 libwebkitgtk-1.0-common libwebkitgtk-3.0-0
  libwebkitgtk-3.0-common
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  libwebkitgtk-1.0-0 mdm
0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
After this operation, 42.9 MB disk space will be freed.
Do you want to continue? [Y/n] 

```

I suppose that this means that if you use "libwebkitgtk-3.0-0" in future versions of MDM that will save some megabytes.

Thank you very much!

**Comment by dg1727** [comment]
This request sounds like something the developers expressed interest in doing in https://github.com/linuxmint/mdm/issues/96#issuecomment-46760487.

**Comment by xenopeek** [comment]
As this issue isn't preventing MDM from working and Linux Mint has moved to use LightDM I'm closing this issue for now.
