### ISSUE TITLE
After updating LibreOffice displaying login screen.

### ISSUE THREAD

**Issue by Faust30000** [linuxmint/mdm#211]
After updating LibreOffice from their official repository to the new version, when you log in, the login screen is displayed. In the settings, auto-login is enabled. It can not be disconnected in any way, it is displayed for 30 seconds.
Linux Mint 18.1 Cinnamon. This problem is only observed in Linux Mint.
Actions: To update LibreOffice we add a repository sudo add-apt-repository ppa:libreoffice/ppa
We are updating the system. Installing the new version.
After that, when you log in, the login screen appears. Even in the settings auto-login is enabled.

**Comment by xenopeek** [comment]
I think this is unrelated to LibreOffice and instead is same issue as #196.
