### ISSUE TITLE
don't start ssh-agent

### ISSUE THREAD

**Issue by jamincollins** [linuxmint/mdm#212]
Currently, mdm will wrap the session command with ssh-agent if it is found on the system:
https://github.com/linuxmint/mdm/blob/c52d76eef9726ca7319b4c9ab565b3420e43a000/config/Xsession.in#L216

However, this can lead to only partially working environments:
- https://bugs.archlinux.org/task/46398

It is better to leave the ssh-agent spawning to the user's environment of choice, rather than having the display manager automatically spawn it (in an incomplete fashion) without the option to disable such behavior.

**Comment by jamincollins** [comment]
It's been a while, any update?

**Comment by jamincollins** [comment]
Any update?

**Comment by xenopeek** [comment]
Thanks for contributing to MDM. Considering Linux Mint has moved to use LightDM with Linux Mint's Slick Greeter I don't think this will see an implementation unless somebody does a PR. I'm closing this issue for now.

**Comment by MarcinWieczorek** [comment]
Nobody will ever see and resolve this issue if you close it. Just saying.
