### ISSUE TITLE
Disappearing password prompt on initial 18.1 Cinnamon password dialog.

### ISSUE THREAD

**Issue by jgoldgh** [linuxmint/mdm#213]
I understand this was a problem in prior releases that was fixed.  I've got two machines running Linux Mint 18.1 64 bit. They were both installed from the ISO I downloaded in early January 2017.  I've installed all updates and patches.

There are actually two problems.  The password dialog seems to loose focus so the password isn't entered correctly. This is random but common.  If I quickly enter my password after booting, it goes in wrong about half the time.  I've done it very carefully and have seen the cursor disappear from the text box and stop accepting characters. I have to click on the text box to force the focus back before I can enter the password.

The second issue is that when the password is incorrect, the password dialog disappears and I have to hit the up arrow or click on the login name to get it back.  It doesn't do this after the first incorrect password entry.  In other words, the second time I enter an incorrect password the dialog box stays on the screen and the password text box keeps focus.

I've got a desktop machine and a Dell XPS 15 9560 that both have the same behavior.  Both machines are running new i7 processors with NVME SSD drives. Other than that, they're very different.

**Comment by xenopeek** [comment]
How failed authentication is handled depends on the theme. If you still have this issue please share what theme you have selected in Login Window.
