### ISSUE TITLE
systemd service point to non-existent files

### ISSUE THREAD

**Issue by ftoledo** [linuxmint/mdm#217]
Systemd service point to:
` ExecStop=/usr/sbin/mdm-stop`

but debian/rules delete it:

`cd debian/mdm/usr/sbin && rm -f mdm-restart mdm-safe-restart mdm-stop`

**Comment by xenopeek** [comment]
Many thanks for contributing to MDM. As this issue isn't preventing MDM from working and Linux Mint has moved to use LightDM and Linux Mint's Slick Greeter, I'm closing this issue for now.
