### ISSUE TITLE
Start Over button does nothing

### ISSUE THREAD

**Issue by jimc-leones** [linuxmint/mdm#219]
This is for OpenSuSE Tumbleweed 2017-08-26 and mdm-2.0.18-2.7.x86_64.  
I'm using a custom theme similar to "Circles", attached.  
/etc/mdm/custom.conf is also attached.  

[couchnet.xml.txt](https://github.com/linuxmint/mdm/files/1285870/couchnet.xml.txt)
[custom.conf.txt](https://github.com/linuxmint/mdm/files/1285879/custom.conf.txt)

Initially I was puzzled that the greeter was not asking for my loginID,
but I spotted SelectLastLogin=true and learned that that's not a bug, 
that's a feature :-)  

However, if I'm a different user how do I give my loginID?  Hit the
Start Again button.  Except it does not start again; it's greyed out.
(Workaround: give a garbage password, it will fail to log in the
preselected user, and it will ask for the loginID again.)  Identical
behavior is seen on "Circles".

The actual behavior is peculiar: without a preselected user, e.g. after
an intentional login failure, it asks for the loginID and Start Again is
greyed out.  When you hit Enter (or OK?  not tested) it hides the
loginID widget and brings out the Password widget, and Start Again
becomes active (not grey).  On the other hand, when a user is
preselected it starts with the Password widget visible and Start Again
greyed out, which is the bug being complained about.  

Maybe the best GUI design is to have Start Again always active.  It doesn't 
hurt you if the loginID is being solicited, the user has hopelessly mistyped 
his loginID, and he uses this means (vs. the backspace key) to clear the 
greeter.

**Comment by xenopeek** [comment]
You should use a GDM theme with a userlist if you set "Automatically select the last logged in user" in options. So you can see which user is selected and change it. For GDM themes without a userlist unset "Automatically select the last logged in user". You could rebase your custom theme on Simple UserList for example.
