### ISSUE TITLE
How to specify the location of .xsession-errors file?

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/mdm#221]
Hi all,
I'd like to customize the location of .xsession-errors file from the usual `$HOME/.xsession-errors`. I've looked at some guides and they suggest placing something like: `ERRFILE=<PATH>/.xsession-errors`  in `/etc/X11/Xsession`. That doesn't work with mdm. I've also tried placing ERRFILE variable into `/etc/mdm/Xsession` but that didn't have any effect either.

Is there a way to specify a custom location with mdm?
Thanks!

**Comment by xenopeek** [comment]
It appears to be hardcoded in function open_xsession_errors in daemon/slave.c https://github.com/linuxmint/mdm/blob/151fa9ed1575d8ae65ebb9453de9e76c76fe7718/daemon/slave.c#L2762. You could consult the documentation on whether there is another option; see my comment here on how to access the documentation https://github.com/linuxmint/mdm/issues/222#issuecomment-361085764. For further support with using MDM please use the forums https://forums.linuxmint.com/viewforum.php?f=47.
