### ISSUE TITLE
What is the chooser section for in mdm.conf?

### ISSUE THREAD

**Issue by hanzo2001** [linuxmint/mdm#222]
I'm diving into `mdm/config/mdm.conf-custom.in` and ` mdm/config/mdm.conf.in` because I want to understand what I can do as an administrator.

The custom file is empty and ready to be populated and it's what I find in my distribution's etc directory. In this file I find an options section called `[chooser]`. However, when looking for info on this section in **mdm.conf.in** there is nothing to be found.

I've been having problems configuring my MDM and I suspect that I may be putting options in the wrong section. Am I correct in suspecting that my configuration isn't working because of this?

If I could understand the C code behind MDM, I would gladly put in the time to update the documentation myself. I tried but I didn't have to go too far to understand that I was in way over my head.

**Comment by xenopeek** [comment]
Seeing as MDM is a fork of GDM 2.x (from GNOME 2, not current 3.x from GNOME 3) I think you can use information for the gdm.conf file for that version. For example I found this one https://www.ibiblio.org/oswg/oswg-nightly/oswg/en_US.ISO_8859-1/articles/gdm-reference/gdm-reference/x135.html
