### ISSUE TITLE
Password box invisible in multi-user setup

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mdm#225]
An issue that I have noticed since Mint 19 beta (see "On a VirtualBox setup..." at https://blog.linuxmint.com/?p=3582): The password box is sometimes cut off for an individual user on a multi-user setup. There is a possibility that this may only occur on reboot. 

I've seen this happen in various circumstances, but to replicate on a non-VM Mint 19.1 MATE setup:

```
Control Centre->Administration->Users and Groups->Add: User1/user1/user1pass.
Repeat for User2.
Close Users Settings window
Reboot machine.
Click on User1.
```

Note that the password box is invisible. You can still click where it should be and enter the password but nothing displays whatsoever. If you imagine the entire user login box as two lines - the username on top and the password area below - surrounded by a curved box, then only the upper half of that box is visible.

I have taken a photo of the login window illustrating the issue as described above but GitHub says that it can't process the file when I try dragging it to this window.

**Comment by xenopeek** [comment]
Linux Mint 19.1 MATE doesn't use MDM as display manager, it uses LightDM (from the Ubuntu 18.04 repo). Can you confirm you have indeed replaced LightDM with MDM? If so, please upload the photo on an image sharing site like https://imgur.com/ and post the link here.

If you made a mistake and you're using LightDM then I'd ask if you could reproduce this with Ubuntu 18.04 VM. If it's not reproducible on that—making it suspect something on Linux Mint end (the theme?) causes this—I'd suggest to make a new issue on https://github.com/linuxmint/linuxmint. If you can reproduce it on Ubuntu 18.04 VM I'd suggest to file issue on LightDM for that.

**Comment by ewangi** [comment]
Thanks for replying xenopeek. All I can say is drat - I had forgotten that Mint now uses LightDM, which indeed I am also using. I'll load an Ubuntu 18.04 VM as advised and see if I can replicate the issue.

**Comment by ewangi** [comment]
I've just tested this on a fully updated Ubuntu 18.04.1 MATE VM and the issue doesn't occur when the steps in the opening post are carried out. I'll create a new issue as suggested. Closing this one with my apologies that it has nothing to do with mdm...
