### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by AndreiMiculita** [linuxmint/mdm#229]
Is this repo still active? I see the last commit was in 2018, while https://github.com/linuxmint/lightdm-settings got an update 2 months ago

Might it make sense to put up a notice that this is no longer being developed/used?

**Comment by Totallynotmwa** [comment]
I am pretty sure they went from using mdm to lightdm

**Comment by AndreiMiculita** [comment]
@clefebvre can you archive this repo?
