### ISSUE TITLE
Infinality patches prevent MDM from starting

### ISSUE THREAD

**Issue by megri** [linuxmint/mdm#49]
Steps to reproduce:
1. Install Linux Mint 15 / Cinnamon
2. Install the infinality patches from https://launchpad.net/~no1wantdthisname/+archive/ppa
3. MDM will be unable to launch on boot and drop the user off at the console login. Note that logging in and manually launching MDM using 'sudo mdm' is working.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mdm/commit/ee1a28b3c295c283aa94b890658d78be25e31bb7
