### ISSUE TITLE
MDM doesn't start at boot after a not-to-recent update.

### ISSUE THREAD

**Issue by MiY4Gi** [linuxmint/mdm#50]
At startup the diagnostic messages shows "fail" next to MDM, and the bootup hangs. So each time I boot I must drop to a shell, log in, then enter "mdm" to start it manually. Then I can log in like normal. 

This might be related to the Infinality patches another user is reporting, but I installed Infinality a long time ago. It started happening after a reboot a couple of weeks back (I hardly ever reboot). I'm currently running Mint 14 Nadia, with the Cinnamon Nightly (i.e. the latest updates).

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mdm/commit/ee1a28b3c295c283aa94b890658d78be25e31bb7
