### ISSUE TITLE
Guest session in MDM

### ISSUE THREAD

**Issue by KDB2** [linuxmint/mdm#51]
Hi !

That would be great if MDM could include a guest session as it was defined in GDM.

This guest session allows all the user to launch an account, where all the modifications are deleted at the end of the use. This account doesn't appear in the user list and can only be launch with an other account.

It's nice when a friend want to use your computer.

**Comment by gauravjuvekar** [comment]
@RavetcoFX Any updates on this?

**Comment by edmundlaugasson** [comment]
I would also expect guest session very much. Especially for public computers it would be very useful. I noticed at http://segfault.linuxmint.com/2013/10/cinnamon-2-0-released/ that there would be some kind of guest session support but it seems like for LightDM users only. Under "Other improvements" there is written: "Added support for LightDM user-switching and guest user sessions"...

**Comment by MrksKwsnck** [comment]
Any update on the guest session implementation? I would appreciate that very much.

**Comment by rawler** [comment]
Same here. Have a work laptop that I would like to let my SO use a little now and then for light surfing, without handing over sensitive work credentials
