### ISSUE TITLE
mdm-binary: GLib-CRITICAL: g_key_file_get_value: assertion 'key_file != NULL' failed

### ISSUE THREAD

**Issue by ghost** [linuxmint/mdm#76]
MDM 1.4.8 creates many assertions on startup. I don't know if it was already present in earlier builds of mdm since there is no issues in using it. Searching the internet, it seems to only happening with gdm2 in old days. Maybe this is a missed regression which is still present in mdm.

<pre>[phil@manjaro journal]$ pacman -Q mdm
mdm 1.4.8-1</pre>

Form systemd-journal:

<pre>Jan 05 00:03:51 manjaro mdm-binary[954]: GLib-CRITICAL: g_key_file_get_value: assertion 'key_file != NULL' failed
...
Jan 05 00:03:51 manjaro mdm-binary[954]: GLib-CRITICAL: g_key_file_get_value: assertion 'key_file != NULL' failed
Jan 05 00:03:51 manjaro mdm-binary[954]: GLib-CRITICAL: g_key_file_get_locale_string: assertion 'key_file != NULL' failed
...
Jan 05 00:03:51 manjaro mdm-binary[954]: GLib-CRITICAL: g_key_file_get_value: assertion 'key_file != NULL' failed</pre>

If you need more informaiton about this issue, let me know.

**Comment by redr00k** [comment]
Hi, I am getting this exact error with LMDE 3.16.0.4-amd64 Any ideas how I can fix?  Pacman not present

**Comment by eriksandberg** [comment]
I'm also suddenly getting this problem on the same version of LMDE as redr00k.

**Comment by clefebvre** [comment]
Hi,

distro.conf is where distributions configure the MDM defaults. Here is the one we're using:

```
[daemon]
Greeter=/usr/lib/mdm/mdmwebkit
DefaultSessions=cinnamon.desktop,mate.desktop,xfce.desktop,kde-plasma.desktop,kde.desktop,plasma.desktop

[gui]
GtkTheme=Mint-X

[greeter]
DefaultFace=/usr/share/pixmaps/faces/user-generic.png
ConfigAvailable=false
ChooserButton=false
ShowGnomeFailsafeSession=false
ShowXtermFailsafeSession=false
GraphicalTheme=linuxmint
GraphicalThemeDir=/usr/share/mdm/themes/
HTMLTheme=Mint-X
SoundOnLogin=true
SoundOnLoginFile=/usr/share/sounds/linuxmint-gdm.wav
SoundOnLoginSuccess=true
SoundOnLoginSuccessFile=/usr/share/sounds/linuxmint-login.wav
SoundOnLoginFailure=false
SoundOnLoginFailureFile=/usr/share/sounds/LinuxMint/stereo/dialog-information.ogg

[debug]
Enable=false
```

In order of priority:

/etc/mdm/mdm.conf (configuration set by the user)
/usr/share/mdm/distro.conf (configuration set by the distribution)
/usr/share/mdm/defaults.conf (MDM defaults)

**Comment by uMtMu** [comment]
I am using Linux Mint(17.3) Mate(1.12.0.1-1+rosa). Totally up to date(upgrade && dist-upgrade). I am getting this error when i install emacs 25 according to [this](http://ubuntuhandbook.org/index.php/2016/09/install-gnu-emacs-25-1-in-ubuntu-16-04/). When remove emacs 25 it returns normal. 

I have /usr/share/mdm/distro.conf file and same as clefebvre's file except 3rd line.
