### ISSUE TITLE
Timed Login for User doesn't work if home folder is encrypted

### ISSUE THREAD

**Issue by loc4lhost** [linuxmint/mdm#84]
Hey Guys,

is this a bug/issue or a correct working thing: if i encrypt my home folder during the installation and want to change the login setting for mdm to timed login with 10 seconds i get the error "could not update ICEauthority file /home/username/.ICEauthority" and a button that shows "log off  user".

best regards,
loc4lhost

**Comment by veeYceeY** [comment]
i am getting the same error from live usb boot
tried stopping mdm ,and startx fails
