### ISSUE TITLE
Unable to log into cinnamon-session after 2.2 update

### ISSUE THREAD

**Issue by ronasimi** [linuxmint/mdm#87]
Arch/Cinnamon/Nvidia 337

I reported a bug on bugs.archlinux.org, but MDM is not a supported display manager on Arch.
see: https://bugs.archlinux.org/task/39899

**Comment by monsta** [comment]
Hmm...
```extra/gnome-keyring 3.10.1-2 -> 3.12.0-1```
Should be fixed now as https://github.com/linuxmint/mdm/issues/92 is fixed.
