### ISSUE TITLE
mdm black screen hang on logout after user switch (Mint 16 Petra, and Mint 17 Qiana). (Workaround found).

### ISSUE THREAD

**Issue by gav-** [linuxmint/mdm#90]
I have a new Mint 16 Petra installation that is dropping to a black screen on logout after switching to a different user and back again. To verify the issue, I have successfully repeated the problem in a VirtualBox VM.

System details:
- Oracle VirtualBox 4.2.24
- Mint 16 MATE 64bit with defaults, no disk encryption. All updates applied.
- Two users 'test1' and 'test2'.

Procedure to repeat bug:
 1) Boot system to mdm login screen.
 2) Login as 'test1'
 3) Menu -> Logout -> Switch User
 4) Login as 'test2'
 5) Menu -> Logout -> Switch User
 6) Login as 'test1' (already logged in)
 7) Menu -> Logout -> Log Out
 8) Login as 'test2' (already logged in)
 9) Menu -> Logout -> Log Out
 10) Stuck in black screen, appears that X is not running on tty.

To recover system:
 1) Move to another tty and login as root.
 2) Identify mdmwebkit process and kill it
 3) X and mdm are now functioning again.

Other notes:
- Changing the login greeter 'theme' does not resolve the problem, same fault exists with GDM (mdmgreeter) and  GTK (mdmlogin).
- The described process is the simplest repeatable mechanism, the problem also appears after other user switching combinations, which is making Mint 16 completely unusable for non-privileged users of a shared system.

10th Sep 2014:

As a workaround to this problem, lightdm may be used as an mdm replacement.

Note: mdm needs to be removed for user switching to work, otherwise you just get a message that "MDM (MDM Display Manager) is not running".

```
apt-get install lightdm lightdm-gtk-greeter
apt-get purge mdm
```

**Comment by gav-** [comment]
Just confirming that MDM 1.8.3 as distributed by Mint 17.1 "Rebecca" does resolve this issue. Thanks clefebvre.

**Comment by marcelverdonk** [comment]
Hello, am I right in thinking that this problem has returned in Mint 17.3? I've just installed it and am seeing exactly the same behaviour that was described here. Any help would be appreciated!

**Comment by hellwoodfire** [comment]
Do you have a nvidia video card ?  I yes, check my last post in this
thread:
http://forums.linuxmint.com/viewtopic.php?f=56&t=173115

2016-01-19 16:07 GMT-05:00 marcelverdonk <notifications@github.com>:

**Comment by marcelverdonk** [comment]
I don't think so, on System Info it says: Intel Corporation ValleyView Gen7

**Comment by sv0** [comment]
I have the same problem with Linux Mint 17.3 Rosa 
EDITION: MATE 64-bit

**Comment by xPrzybyLx** [comment]
This issue is back in Linux Mint 17.3 and 18 xfce editions.

Nvidia drivers: 367.35 on GTX  970

I have black screen right after mdm start and I have to switch to console and back to display it properly. Then I can log in.

**Comment by chrisonhub** [comment]
I see this bug on occasion with my DELL laptop running intel video and LM 17.3 Cinnamon.  I find it hard to reproduce though - Clem's original patch seems to work most of the time.

**Comment by Dreamwalker420** [comment]
I have a Dell Inspirion i5577, with the Nvidia graphics card as well.  I installed Linux Mint 18.2, and when a user is logged in, and I try to login as another user (the default created at installation), the system hangs.  Unable to reboot.  Manually turn off the computer and then start with recovery is allowed ... but how to solve the problem?
