### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by akstrfn** [linuxmint/mdm#97]
At login screen if HTML layout is selected I get high cpu usage and my fan start blowing all the time and it does so until I log in. I use GDM login and all is fine. This was the problem for me in the last 3 versions of Linux Mint (thats when I started using LM).
![img_20140610_114131](https://cloud.githubusercontent.com/assets/6161338/3230882/4d7e8f18-f0a7-11e3-8885-e4322ec4f0ac.jpg)

Same is happening weather I use open source graphic driver or proprietary. At the moment I use fglrx proprietary driver (available in repositories) on fresh LM 17 install.
Also it seems that even when I log in my memory consumption is about 40mb higher when I log over HTML that GDM (i.e. 620mb vs 580) though I haven't bothered to check this in details so it could be nothing.

**Comment by adeverteuil** [comment]
Hi,

Here is a workaround. Comment out the play() method in `/usr/share/mdm/html-themes/Mint-X/index.html`. This stops the scrolling gradient animation. The CPU usage is now normal and no other functionality is lost.

Source : http://forum.linuxmint.com/viewtopic.php?p=964853#p926295
